services:
  db:
    image: postgis/postgis:16-3.4
    container_name: messless-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: messless
    ports:
      - "5440:5432"
    volumes:
      - messless_db_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  messless_db_data: