ktor:
  environment: ${KTOR_ENV:dev}
  application:
    modules:
      - at.eventful.messless.ApplicationKt.module
  deployment:
    port: ${PORT:8080}

messless:
  db:
    driver: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql://localhost:5440/messless}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

    dump:
      dir: "src/main/resources/db/dump/"
      name: "full_dump"

    migrations:
      dir: "src/main/resources/db/migrations/"

  jwt:
    secret: ${JWT_SECRET:dev-secret}
    issuer: "messless"
    audience: "msls frontends"
    realm: "main"