ktor:
  environment: $?KTOR_ENV:dev
  application:
    modules:
      - at.eventful.messless.ApplicationKt.module
  deployment:
    port: $PORT:8080

messless:
  db:
    migrations:
      dir: "src/main/resources/db/migrations/"
      current: "V0.0.0__initial"
    dev:
      driver: "org.h2.Driver"
      url: "jdbc:h2:mem:messlessBackendTest;DB_CLOSE_DELAY=-1"
      user: "tester"
      password: ""
