ktor:
  environment: ${KTOR_ENV:dev}
  application:
    modules:
      - at.eventful.messless.ApplicationKt.module
  deployment:
    port: $PORT:8080

messless:
  db:
    dump:
      dir: "src/main/resources/db/dump/"
      name: "full_dump.sql"
    migrations:
      dir: "src/main/resources/db/migrations/"
    dev:
      driver: "org.h2.Driver"
      url: "jdbc:h2:mem:messlessBackendTest;DB_CLOSE_DELAY=-1"
      user: "tester"
      password: ""
  jwt:
    secret: $JWT_SECRET
    issuer: "messless"
    audience: "msls frontends"
    realm: "main"