CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS COMPANIES (
    ID SERIAL PRIMARY KEY,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NULL,
    DELETED_AT TIMESTAMP(6) NULL,
    LABEL VARCHAR(255) NOT NULL,
    LOCATION GEOMETRY(POINT, 4326) NOT NULL
    );

CREATE TABLE IF NOT EXISTS EQUIPMENT_STORAGES (
    ID SERIAL PRIMARY KEY,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NULL,
    DELETED_AT TIMESTAMP(6) NULL,
    LABEL VARCHAR(255) NOT NULL,
    LOCATION GEOMETRY(POINT, 4326) NOT NULL
    );

CREATE TABLE IF NOT EXISTS WAREHOUSES (
    ID SERIAL PRIMARY KEY,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NULL,
    DELETED_AT TIMESTAMP(6) NULL,
    LABEL VARCHAR(255) NOT NULL,
    LOCATION GEOMETRY(POINT, 4326) NOT NULL,
    COMPANY_ID INT NOT NULL,
    CONSTRAINT FK_WAREHOUSES_COMPANY_ID__ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID) ON DELETE RESTRICT
    );

CREATE TABLE IF NOT EXISTS EQUIPMENT (
    ID SERIAL PRIMARY KEY,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NULL,
    DELETED_AT TIMESTAMP(6) NULL,
    LABEL VARCHAR(255) NOT NULL,
    LOCATION GEOMETRY(POINT, 4326) NOT NULL,
    WAREHOUSE_ID INT NOT NULL,
    STORAGE_ID INT NULL,
    CONSTRAINT FK_EQUIPMENT_WAREHOUSE_ID__ID FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES(ID) ON DELETE RESTRICT,
    CONSTRAINT FK_EQUIPMENT_STORAGE_ID__ID FOREIGN KEY (STORAGE_ID) REFERENCES EQUIPMENT_STORAGES(ID) ON DELETE RESTRICT
    );

CREATE TABLE IF NOT EXISTS EVENTS (
    ID SERIAL PRIMARY KEY,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NULL,
    DELETED_AT TIMESTAMP(6) NULL,
    LABEL VARCHAR(255) NOT NULL,
    LOCATION GEOMETRY(POINT, 4326) NOT NULL
    );

CREATE TABLE IF NOT EXISTS USERS (
    ID SERIAL PRIMARY KEY,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NULL,
    DELETED_AT TIMESTAMP(6) NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    COMPANY_ID INT NULL,
    CONSTRAINT FK_USERS_COMPANY_ID__ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID) ON DELETE RESTRICT
    );

CREATE TABLE IF NOT EXISTS TECHNICAL_LOG_ENTRIES (
    ID SERIAL PRIMARY KEY,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NULL,
    DELETED_AT TIMESTAMP(6) NULL,
    IS_CHECK_IN BOOLEAN NOT NULL,
    EQUIPMENT_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    LOGGABLE INT NOT NULL,
    CONSTRAINT FK_TECHNICAL_LOG_ENTRIES_EQUIPMENT_ID__ID FOREIGN KEY (EQUIPMENT_ID) REFERENCES EQUIPMENT(ID) ON DELETE RESTRICT,
    CONSTRAINT FK_TECHNICAL_LOG_ENTRIES_USER_ID__ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE RESTRICT
    );