CREATE TABLE IF NOT EXISTS loggable (id SERIAL PRIMARY KEY, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NULL, deleted_at TIMESTAMP NULL, "label" VARCHAR(255) NOT NULL, "location" GEOMETRY(POINT, 4326) NOT NULL, loggable_type VARCHAR(20) NOT NULL, company_id INT NOT NULL, CONSTRAINT fk_loggable_company_id__id FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE SEQUENCE IF NOT EXISTS loggable_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
ALTER TABLE equipment_storages ADD loggable INT NOT NULL;
ALTER TABLE events ADD loggable INT NOT NULL;
ALTER TABLE warehouses ADD loggable INT NOT NULL;
ALTER TABLE equipment_storages ADD CONSTRAINT fk_equipment_storages_loggable__id FOREIGN KEY (loggable) REFERENCES loggable(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE equipment DROP CONSTRAINT fk_equipment_warehouse_id__id;
ALTER TABLE equipment ADD CONSTRAINT fk_equipment_warehouse_id__id FOREIGN KEY (warehouse_id) REFERENCES warehouses(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE equipment DROP CONSTRAINT fk_equipment_storage_id__id;
ALTER TABLE equipment ADD CONSTRAINT fk_equipment_storage_id__id FOREIGN KEY (storage_id) REFERENCES equipment_storages(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE events ADD CONSTRAINT fk_events_loggable__id FOREIGN KEY (loggable) REFERENCES loggable(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE technical_log_entries DROP CONSTRAINT fk_technical_log_entries_equipment_id__id;
ALTER TABLE technical_log_entries ADD CONSTRAINT fk_technical_log_entries_equipment_id__id FOREIGN KEY (equipment_id) REFERENCES equipment(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE technical_log_entries DROP CONSTRAINT fk_technical_log_entries_user_id__id;
ALTER TABLE technical_log_entries ADD CONSTRAINT fk_technical_log_entries_user_id__id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE users DROP CONSTRAINT fk_users_company_id__id;
ALTER TABLE users ADD CONSTRAINT fk_users_company_id__id FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE warehouses DROP CONSTRAINT fk_warehouses_company_id__id;
ALTER TABLE warehouses ADD CONSTRAINT fk_warehouses_company_id__id FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE warehouses ADD CONSTRAINT fk_warehouses_loggable__id FOREIGN KEY (loggable) REFERENCES loggable(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE equipment_storages DROP COLUMN IF EXISTS "label";
ALTER TABLE equipment_storages DROP COLUMN IF EXISTS "location";
ALTER TABLE equipment DROP COLUMN IF EXISTS "location";
ALTER TABLE events DROP COLUMN IF EXISTS "label";
ALTER TABLE events DROP COLUMN IF EXISTS "location";
ALTER TABLE warehouses DROP COLUMN IF EXISTS "label";
ALTER TABLE warehouses DROP COLUMN IF EXISTS "location";
